//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabTest()
        {
            this.LabOrders = new HashSet<LabOrder>();
        }
    
        public int Id { get; set; }
        public string LabTestName { get; set; }
        public string LabTestCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabOrder> LabOrders { get; set; }
    }
}
